root: true

env:
  node: true
  es6: true

extends:
  - plugin:vue/vue3-recommended
  - eslint:recommended
  - plugin:prettier/recommended
  - eslint-config-prettier

globals:
  __VERSION__: 'readonly'
  __DEV__: 'readonly'
  __SSR__: 'readonly'
  __VUE_HMR_RUNTIME__: 'writable'

ignorePatterns:
  - '**/dist/**'
  - '**/node_modules/**'
  - '.cache/**'
  - '.temp/**'

overrides:
  - files:
      - '*.vue'

    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:prettier/recommended
      - '@vue/typescript/recommended'
      - '@vue/prettier'
      - '@vue/prettier/@typescript-eslint'

    plugins:
      - '@typescript-eslint'

    parser: vue-eslint-parser

    parserOptions:
      extraFileExtensions:
        - .vue
      parser: '@typescript-eslint/parser'

    rules:
      '@typescript-eslint/explicit-function-return-type':
        - warn
        - allowTypedFunctionExpressions: true

      '@typescript-eslint/naming-convention':
        - warn
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - variable
          format:
            - camelCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - property
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

      '@typescript-eslint/no-explicit-any':
        - warn
        - ignoreRestArgs: true

  - files:
      - '*.ts'

    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - plugin:prettier/recommended

    plugins:
      - '@typescript-eslint'

    parser: vue-eslint-parser

    parserOptions:
      parser: '@typescript-eslint/parser'
      project:
        - './tsconfig.json'
        - './tsconfig.eslint.json'

    rules:
      '@typescript-eslint/explicit-function-return-type':
        - warn
        - allowTypedFunctionExpressions: true

      '@typescript-eslint/ban-types':
        - 0

      '@typescript-eslint/no-this-alias':
        - 0

      '@typescript-eslint/no-unsafe-assignment':
        - 0

      '@eslint-plugin/explicit-function-return-type':
        - 0

      '@typescript-eslint/restrict-template-expressions':
        - 0

      '@typescript-eslint/ban-ts-comment':
        - warn

      '@typescript-eslint/naming-convention':
        - warn
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - variable
          format:
            - camelCase
            - PascalCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - parameter
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - property
          format:
            - camelCase
            - PascalCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

      '@typescript-eslint/no-explicit-any':
        - warn
        - ignoreRestArgs: true

      '@typescript-eslint/no-unsafe-member-access':
        - warn

  - files:
      - '*.d.ts'
    rules:
      no-underscore-dangle:
        - off

  - files:
      - '**/tests/*.spec.{j,t}s?(x)'

    env:
      jest: true

    rules:
      '@typescript-eslint/no-explicit-any':
        - off
      '@typescript-eslint/no-unsafe-call':
        - off
      '@typescript-eslint/no-unsafe-assignment':
        - off
      '@typescript-eslint/no-unsafe-member-access':
        - off
