name: Check

on:
  push:
    branches:
      - dev
      - next
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - dev
      - next
      - main
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # cache node_modules
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.1
        with:
          version: latest
          run_install: true

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm build

      - name: Build project (MPA)
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm build-mpa

      - name: Linter test
        run: |
          pnpm run lint:check
          pnpm run lint:md
          pnpm run lint:eslint
          pnpm run lint:zh
