name: Links (Fail Fast)

on:
  push:
    branches:
      - dev
      - next
      - main

    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - dev
      - next
      - main
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
